EXE = ej3
OBJS = ej3.o TestCaseEj3.o #Tablero.o IndiceDePiezas.o IteradorIndiceDePiezas.o IteradorMedio.o IteradorPrimeraFila.o IteradorPrimeraColumna.o IteradorPrimerCasillero.o

include ../Makefile.gen
