EXE = ej3
OBJS = ej3.o TestCaseEj3.o Tablero.o IndiceDePiezas.o IteradorIndiceDePiezas.o IteradorNormal.o #IteradorPrimeraFila.o IteradorPrimeraColumna.o IteradorPrimerCasillero.o
OBJS:=ej3.o IteradorSecuencial.o TestCaseEj3.o Tablero.o IteradorIndiceDePiezas.o IndiceDePiezas.o 

include ../Makefile.gen
