EXE = ej3
OBJS = ej3.o TestCaseEj3.o Tablero.o IndiceDePiezas.o IteradorIndiceDePiezas.o IteradorNormal.o #IteradorPrimeraFila.o IteradorPrimeraColumna.o IteradorPrimerCasillero.o
OBJS:=ej3.o IteradorColores.o IteradorSecuencial.o TestCaseEj3.o Tablero.o IteradorIndiceDePiezas.o IndiceDePiezas.o 

TARGETS:= ej3.time.sinPodaObjetivo ej3.time.sinPodaSeleccion ej3.time.sinPodas

include ../Makefile.gen
